application: twilioapi
version: 1
runtime: python
api_version: 1

handlers:
- url: /Callbacks/.*
  script: handlers/callbacks.py
  login: admin

- url: /(.*)/Accounts/(.*)/SMS/.*
  script: handlers/sms.py

#/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{IsoCountryCode}/Local
- url: /(.*)/Accounts/(.*)/AvailablePhoneNumbers/(.*)/Local
  script: handlers/phone_numbers.py
- url: /(.*)/Accounts/(.*)/AvailablePhoneNumbers/(.*)/TollFree
  script: handlers/phone_numbers.py

- url: /(.*)/Accounts/.*
  script: handlers/accounts.py

- url: .*
  script: handlers/main.py
  secure: always
