application: twilioapi
version: 1
runtime: python
api_version: 1

handlers:
    
- url: /examples/twiml
  static_dir: examples/twiml

- url: /test.*
  script: gaeunit.py

#Handler for all callbacks as of right now.
- url: /Callbacks/.*
  script: handlers/callbacks.py
  login: admin

#/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{IsoCountryCode}/Local
- url: /(.*)/Accounts/(.*)/AvailablePhoneNumbers/(.*)/Local
  script: handlers/available_phone_numbers.py
- url: /(.*)/Accounts/(.*)/AvailablePhoneNumbers/(.*)/TollFree
  script: handlers/available_phone_numbers.py

# /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{OutgoingCallerIdSid}
- url: /(.*)/Accounts/(.*)/OutgoingCallerIds/.*
  script: handlers/outgoing_caller_ids.py

# /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{IncomingPhoneNumberSid}
- url: /(.*)/Accounts/(.*)/IncomingPhoneNumbers/.*
  script: handlers/incoming_phone_numbers.py
- url: /(.*)/Accounts/(.*)/IncomingPhoneNumbers.*
  script: handlers/incoming_phone_numbers.py

# /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}
# /2010-04-01/Accounts/{AccountSid}/Calls
- url: /(.*)/Accounts/(.*)/Calls/.*
  script: handlers/calls.py
- url: /(.*)/Accounts/(.*)/Calls
  script: handlers/calls.py

# /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}
- url: /(.*)/Accounts/(.*)/Conferences/.*
  script: handlers/conferences.py
- url: /(.*)/Accounts/(.*)/Conferences
  script: handlers/conferences.py

# /2010-04-01/Accounts/{AccountSid}/SMS/Messages/{SMSMessageSid}
- url: /(.*)/Accounts/(.*)/SMS/.*
  script: handlers/sms.py

# /2010-04-01/Accounts/{AccountSid}/Recordings/{RecordingSid}
- url: /(.*)/Accounts/(.*)/Recordings/.*
  script: handlers/recordings.py

# /2010-04-01/Accounts/{AccountSid}/Transcriptions/{TranscriptionSid}
- url: /(.*)/Accounts/(.*)/Transcriptions/.*
  script: handlers/transcriptions.py

# /2010-04-01/Accounts/{AccountSid}/Notifications/{NotificationSid}
- url: /(.*)/Accounts/(.*)/Notifications/.*
  script: handlers/notifications.py

# /2010-04-01/Accounts/{YourAccountSid}/Sandbox
- url: /(.*)/Accounts/(.*)/Sandbox
  script: handlers/sandbox.py

# /2010-04-01/Accounts/{YourAccountSid}
- url: /(.*)/Accounts/.*
  script: handlers/accounts.py


# Application URL
- url: .*
  script: handlers/main.py
  secure: always